# Generated by Django 5.2.7 on 2025-11-06 15:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConstructionCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_limit', models.DecimalField(decimal_places=2, help_text='Maximum amount that can be disbursed.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_monthly_draw_rate', models.DecimalField(decimal_places=4, help_text='Monthly draw cap expressed as a fraction of the total limit (e.g. 0.08).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('start_period', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('end_period', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('annual_interest_rate', models.DecimalField(decimal_places=4, help_text='Annual nominal rate expressed as a fraction (e.g. 0.12).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='construction_credit', to='finance.project')),
            ],
            options={
                'ordering': ('project__name',),
            },
        ),
        migrations.CreateModel(
            name='SubStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_stages', to='finance.project')),
            ],
            options={
                'ordering': ('project__name', 'name'),
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CreditDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_draws', to='finance.constructioncredit')),
            ],
            options={
                'ordering': ('period',),
                'unique_together': {('credit', 'period')},
            },
        ),
        migrations.CreateModel(
            name='CapitalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_contributions', to='finance.project')),
            ],
            options={
                'ordering': ('period',),
                'unique_together': {('project', 'period')},
            },
        ),
        migrations.CreateModel(
            name='CashFlowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('concept', models.CharField(choices=[('income', 'Income'), ('cost', 'Cost')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sub_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_entries', to='finance.substage')),
            ],
            options={
                'ordering': ('period', 'sub_stage__name'),
                'unique_together': {('sub_stage', 'period', 'concept')},
            },
        ),
    ]
